// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/francobatta/iol-challenge/notification-system/api/internal/audience (interfaces: Repository)
//
// Generated by this command:
//
//	mockgen -destination=audiencetest/mock_repository.go -package=audiencetest . Repository
//

// Package audiencetest is a generated GoMock package.
package audiencetest

import (
	context "context"
	reflect "reflect"

	audience "github.com/francobatta/iol-challenge/notification-system/api/internal/audience"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// AddMembers mocks base method.
func (m *MockRepository) AddMembers(ctx context.Context, appID, listID string, userIDs []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddMembers", ctx, appID, listID, userIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddMembers indicates an expected call of AddMembers.
func (mr *MockRepositoryMockRecorder) AddMembers(ctx, appID, listID, userIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddMembers", reflect.TypeOf((*MockRepository)(nil).AddMembers), ctx, appID, listID, userIDs)
}

// CreateApp mocks base method.
func (m *MockRepository) CreateApp(ctx context.Context, name string) (audience.App, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateApp", ctx, name)
	ret0, _ := ret[0].(audience.App)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateApp indicates an expected call of CreateApp.
func (mr *MockRepositoryMockRecorder) CreateApp(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateApp", reflect.TypeOf((*MockRepository)(nil).CreateApp), ctx, name)
}

// CreateEndpoint mocks base method.
func (m *MockRepository) CreateEndpoint(ctx context.Context, appID string, e audience.Endpoint) (audience.Endpoint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateEndpoint", ctx, appID, e)
	ret0, _ := ret[0].(audience.Endpoint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateEndpoint indicates an expected call of CreateEndpoint.
func (mr *MockRepositoryMockRecorder) CreateEndpoint(ctx, appID, e any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateEndpoint", reflect.TypeOf((*MockRepository)(nil).CreateEndpoint), ctx, appID, e)
}

// CreateList mocks base method.
func (m *MockRepository) CreateList(ctx context.Context, appID string, l audience.List) (audience.List, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateList", ctx, appID, l)
	ret0, _ := ret[0].(audience.List)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateList indicates an expected call of CreateList.
func (mr *MockRepositoryMockRecorder) CreateList(ctx, appID, l any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateList", reflect.TypeOf((*MockRepository)(nil).CreateList), ctx, appID, l)
}

// DeleteEndpoint mocks base method.
func (m *MockRepository) DeleteEndpoint(ctx context.Context, appID, endpointID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteEndpoint", ctx, appID, endpointID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteEndpoint indicates an expected call of DeleteEndpoint.
func (mr *MockRepositoryMockRecorder) DeleteEndpoint(ctx, appID, endpointID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteEndpoint", reflect.TypeOf((*MockRepository)(nil).DeleteEndpoint), ctx, appID, endpointID)
}

// DeleteList mocks base method.
func (m *MockRepository) DeleteList(ctx context.Context, appID, listID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteList", ctx, appID, listID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteList indicates an expected call of DeleteList.
func (mr *MockRepositoryMockRecorder) DeleteList(ctx, appID, listID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteList", reflect.TypeOf((*MockRepository)(nil).DeleteList), ctx, appID, listID)
}

// DeleteUser mocks base method.
func (m *MockRepository) DeleteUser(ctx context.Context, appID, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUser", ctx, appID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUser indicates an expected call of DeleteUser.
func (mr *MockRepositoryMockRecorder) DeleteUser(ctx, appID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUser", reflect.TypeOf((*MockRepository)(nil).DeleteUser), ctx, appID, userID)
}

// Endpoint mocks base method.
func (m *MockRepository) Endpoint(ctx context.Context, appID, endpointID string) (audience.Endpoint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Endpoint", ctx, appID, endpointID)
	ret0, _ := ret[0].(audience.Endpoint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Endpoint indicates an expected call of Endpoint.
func (mr *MockRepositoryMockRecorder) Endpoint(ctx, appID, endpointID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Endpoint", reflect.TypeOf((*MockRepository)(nil).Endpoint), ctx, appID, endpointID)
}

// Endpoints mocks base method.
func (m *MockRepository) Endpoints(ctx context.Context, appID, userID string, p audience.Page) ([]audience.Endpoint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Endpoints", ctx, appID, userID, p)
	ret0, _ := ret[0].([]audience.Endpoint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Endpoints indicates an expected call of Endpoints.
func (mr *MockRepositoryMockRecorder) Endpoints(ctx, appID, userID, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Endpoints", reflect.TypeOf((*MockRepository)(nil).Endpoints), ctx, appID, userID, p)
}

// KnownUsers mocks base method.
func (m *MockRepository) KnownUsers(ctx context.Context, appID string, userIDs []string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "KnownUsers", ctx, appID, userIDs)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// KnownUsers indicates an expected call of KnownUsers.
func (mr *MockRepositoryMockRecorder) KnownUsers(ctx, appID, userIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "KnownUsers", reflect.TypeOf((*MockRepository)(nil).KnownUsers), ctx, appID, userIDs)
}

// List mocks base method.
func (m *MockRepository) List(ctx context.Context, appID, listID string) (audience.List, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, appID, listID)
	ret0, _ := ret[0].(audience.List)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockRepositoryMockRecorder) List(ctx, appID, listID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockRepository)(nil).List), ctx, appID, listID)
}

// Lists mocks base method.
func (m *MockRepository) Lists(ctx context.Context, appID string, p audience.Page) ([]audience.List, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Lists", ctx, appID, p)
	ret0, _ := ret[0].([]audience.List)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Lists indicates an expected call of Lists.
func (mr *MockRepositoryMockRecorder) Lists(ctx, appID, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Lists", reflect.TypeOf((*MockRepository)(nil).Lists), ctx, appID, p)
}

// Members mocks base method.
func (m *MockRepository) Members(ctx context.Context, appID, listID string, p audience.Page) ([]audience.Member, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Members", ctx, appID, listID, p)
	ret0, _ := ret[0].([]audience.Member)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Members indicates an expected call of Members.
func (mr *MockRepositoryMockRecorder) Members(ctx, appID, listID, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Members", reflect.TypeOf((*MockRepository)(nil).Members), ctx, appID, listID, p)
}

// PutUser mocks base method.
func (m *MockRepository) PutUser(ctx context.Context, appID, userID string) (audience.User, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutUser", ctx, appID, userID)
	ret0, _ := ret[0].(audience.User)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// PutUser indicates an expected call of PutUser.
func (mr *MockRepositoryMockRecorder) PutUser(ctx, appID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutUser", reflect.TypeOf((*MockRepository)(nil).PutUser), ctx, appID, userID)
}

// RemoveMember mocks base method.
func (m *MockRepository) RemoveMember(ctx context.Context, appID, listID, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveMember", ctx, appID, listID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveMember indicates an expected call of RemoveMember.
func (mr *MockRepositoryMockRecorder) RemoveMember(ctx, appID, listID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveMember", reflect.TypeOf((*MockRepository)(nil).RemoveMember), ctx, appID, listID, userID)
}

// UpdateEndpoint mocks base method.
func (m *MockRepository) UpdateEndpoint(ctx context.Context, appID string, e audience.Endpoint) (audience.Endpoint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateEndpoint", ctx, appID, e)
	ret0, _ := ret[0].(audience.Endpoint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateEndpoint indicates an expected call of UpdateEndpoint.
func (mr *MockRepositoryMockRecorder) UpdateEndpoint(ctx, appID, e any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateEndpoint", reflect.TypeOf((*MockRepository)(nil).UpdateEndpoint), ctx, appID, e)
}

// UpdateList mocks base method.
func (m *MockRepository) UpdateList(ctx context.Context, appID string, l audience.List) (audience.List, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateList", ctx, appID, l)
	ret0, _ := ret[0].(audience.List)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateList indicates an expected call of UpdateList.
func (mr *MockRepositoryMockRecorder) UpdateList(ctx, appID, l any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateList", reflect.TypeOf((*MockRepository)(nil).UpdateList), ctx, appID, l)
}

// User mocks base method.
func (m *MockRepository) User(ctx context.Context, appID, userID string) (audience.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "User", ctx, appID, userID)
	ret0, _ := ret[0].(audience.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// User indicates an expected call of User.
func (mr *MockRepositoryMockRecorder) User(ctx, appID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "User", reflect.TypeOf((*MockRepository)(nil).User), ctx, appID, userID)
}

// Users mocks base method.
func (m *MockRepository) Users(ctx context.Context, appID string, p audience.Page) ([]audience.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Users", ctx, appID, p)
	ret0, _ := ret[0].([]audience.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Users indicates an expected call of Users.
func (mr *MockRepositoryMockRecorder) Users(ctx, appID, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Users", reflect.TypeOf((*MockRepository)(nil).Users), ctx, appID, p)
}
