// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/francobatta/iol-challenge/notification-system/api/internal/notify (interfaces: Repository)
//
// Generated by this command:
//
//	mockgen -destination=notifytest/mock.go -package=notifytest . Repository
//

// Package notifytest is a generated GoMock package.
package notifytest

import (
	context "context"
	reflect "reflect"

	audience "github.com/francobatta/iol-challenge/notification-system/api/internal/audience"
	notify "github.com/francobatta/iol-challenge/notification-system/api/internal/notify"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// CreateJob mocks base method.
func (m *MockRepository) CreateJob(ctx context.Context, appID string, r notify.Request) (notify.Job, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateJob", ctx, appID, r)
	ret0, _ := ret[0].(notify.Job)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CreateJob indicates an expected call of CreateJob.
func (mr *MockRepositoryMockRecorder) CreateJob(ctx, appID, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateJob", reflect.TypeOf((*MockRepository)(nil).CreateJob), ctx, appID, r)
}

// Job mocks base method.
func (m *MockRepository) Job(ctx context.Context, appID, jobID string) (notify.Job, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Job", ctx, appID, jobID)
	ret0, _ := ret[0].(notify.Job)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Job indicates an expected call of Job.
func (mr *MockRepositoryMockRecorder) Job(ctx, appID, jobID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Job", reflect.TypeOf((*MockRepository)(nil).Job), ctx, appID, jobID)
}

// Jobs mocks base method.
func (m *MockRepository) Jobs(ctx context.Context, appID string, p audience.Page) ([]notify.Job, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Jobs", ctx, appID, p)
	ret0, _ := ret[0].([]notify.Job)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Jobs indicates an expected call of Jobs.
func (mr *MockRepositoryMockRecorder) Jobs(ctx, appID, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Jobs", reflect.TypeOf((*MockRepository)(nil).Jobs), ctx, appID, p)
}

// List mocks base method.
func (m *MockRepository) List(ctx context.Context, appID, listID string) (audience.List, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, appID, listID)
	ret0, _ := ret[0].(audience.List)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockRepositoryMockRecorder) List(ctx, appID, listID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockRepository)(nil).List), ctx, appID, listID)
}

// Quota mocks base method.
func (m *MockRepository) Quota(ctx context.Context, appID string) (int64, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Quota", ctx, appID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Quota indicates an expected call of Quota.
func (mr *MockRepositoryMockRecorder) Quota(ctx, appID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Quota", reflect.TypeOf((*MockRepository)(nil).Quota), ctx, appID)
}
