// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/francobatta/iol-challenge/notification-system/api/internal/dispatch (interfaces: Repository,Publisher)
//
// Generated by this command:
//
//	mockgen -destination=dispatchtest/mock.go -package=dispatchtest . Repository,Publisher
//

// Package dispatchtest is a generated GoMock package.
package dispatchtest

import (
	context "context"
	reflect "reflect"
	time "time"

	dispatch "github.com/francobatta/iol-challenge/notification-system/api/internal/dispatch"
	notify "github.com/francobatta/iol-challenge/notification-system/api/internal/notify"
	message "github.com/francobatta/iol-challenge/notification-system/commons/message"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// AdvanceFanout mocks base method.
func (m *MockRepository) AdvanceFanout(ctx context.Context, j dispatch.Job, cursor string, published int, lease time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AdvanceFanout", ctx, j, cursor, published, lease)
	ret0, _ := ret[0].(error)
	return ret0
}

// AdvanceFanout indicates an expected call of AdvanceFanout.
func (mr *MockRepositoryMockRecorder) AdvanceFanout(ctx, j, cursor, published, lease any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdvanceFanout", reflect.TypeOf((*MockRepository)(nil).AdvanceFanout), ctx, j, cursor, published, lease)
}

// ClaimFanout mocks base method.
func (m *MockRepository) ClaimFanout(ctx context.Context, lease time.Duration) (dispatch.Job, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClaimFanout", ctx, lease)
	ret0, _ := ret[0].(dispatch.Job)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ClaimFanout indicates an expected call of ClaimFanout.
func (mr *MockRepositoryMockRecorder) ClaimFanout(ctx, lease any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClaimFanout", reflect.TypeOf((*MockRepository)(nil).ClaimFanout), ctx, lease)
}

// FanoutPage mocks base method.
func (m *MockRepository) FanoutPage(ctx context.Context, j dispatch.Job, limit int) (dispatch.Page, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FanoutPage", ctx, j, limit)
	ret0, _ := ret[0].(dispatch.Page)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FanoutPage indicates an expected call of FanoutPage.
func (mr *MockRepositoryMockRecorder) FanoutPage(ctx, j, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FanoutPage", reflect.TypeOf((*MockRepository)(nil).FanoutPage), ctx, j, limit)
}

// FinishFanout mocks base method.
func (m *MockRepository) FinishFanout(ctx context.Context, j dispatch.Job, published int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FinishFanout", ctx, j, published)
	ret0, _ := ret[0].(error)
	return ret0
}

// FinishFanout indicates an expected call of FinishFanout.
func (mr *MockRepositoryMockRecorder) FinishFanout(ctx, j, published any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FinishFanout", reflect.TypeOf((*MockRepository)(nil).FinishFanout), ctx, j, published)
}

// MockPublisher is a mock of Publisher interface.
type MockPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockPublisherMockRecorder
	isgomock struct{}
}

// MockPublisherMockRecorder is the mock recorder for MockPublisher.
type MockPublisherMockRecorder struct {
	mock *MockPublisher
}

// NewMockPublisher creates a new mock instance.
func NewMockPublisher(ctrl *gomock.Controller) *MockPublisher {
	mock := &MockPublisher{ctrl: ctrl}
	mock.recorder = &MockPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPublisher) EXPECT() *MockPublisherMockRecorder {
	return m.recorder
}

// PublishDeliveries mocks base method.
func (m *MockPublisher) PublishDeliveries(ctx context.Context, deliveries []message.Delivery, p notify.Priority) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishDeliveries", ctx, deliveries, p)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishDeliveries indicates an expected call of PublishDeliveries.
func (mr *MockPublisherMockRecorder) PublishDeliveries(ctx, deliveries, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishDeliveries", reflect.TypeOf((*MockPublisher)(nil).PublishDeliveries), ctx, deliveries, p)
}
