// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package queries

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type App struct {
	AppID      pgtype.UUID
	Name       string
	CreatedAt  time.Time
	DailyQuota int64
}

type Endpoint struct {
	AppID      pgtype.UUID
	EndpointID pgtype.UUID
	UserID     string
	Address    string
	Channel    string
	Provider   string
}

type Fanout struct {
	AppID      pgtype.UUID
	JobID      pgtype.UUID
	UserCursor string
	RunAfter   time.Time
}

type Job struct {
	AppID          pgtype.UUID
	JobID          pgtype.UUID
	Status         string
	Priority       string
	UserIds        []string
	ListID         pgtype.UUID
	Title          string
	Body           string
	IdempotencyKey pgtype.Text
	Queued         int64
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type List struct {
	AppID       pgtype.UUID
	ListID      pgtype.UUID
	Name        string
	Description string
	CreatedAt   time.Time
}

type ListMember struct {
	AppID   pgtype.UUID
	ListID  pgtype.UUID
	UserID  string
	AddedAt time.Time
}

type UsageDaily struct {
	AppID  pgtype.UUID
	Day    pgtype.Date
	Queued int64
}

type User struct {
	AppID     pgtype.UUID
	UserID    string
	CreatedAt time.Time
}
