// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package queries

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type App struct {
	AppID     pgtype.UUID
	Name      string
	CreatedAt time.Time
}

type Endpoint struct {
	AppID      pgtype.UUID
	EndpointID pgtype.UUID
	UserID     string
	Address    string
	Channel    string
	Provider   string
}

type List struct {
	AppID       pgtype.UUID
	ListID      pgtype.UUID
	Name        string
	Description string
	CreatedAt   time.Time
}

type ListMember struct {
	AppID   pgtype.UUID
	ListID  pgtype.UUID
	UserID  string
	AddedAt time.Time
}

type User struct {
	AppID     pgtype.UUID
	UserID    string
	CreatedAt time.Time
}
