// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package queries

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const addMembers = `-- name: AddMembers :exec
INSERT INTO list_members (app_id, list_id, user_id)
SELECT $1::uuid, $2::uuid, unnest($3::text[])
ON CONFLICT DO NOTHING
`

type AddMembersParams struct {
	AppID   pgtype.UUID
	ListID  pgtype.UUID
	UserIds []string
}

func (q *Queries) AddMembers(ctx context.Context, arg AddMembersParams) error {
	_, err := q.db.Exec(ctx, addMembers, arg.AppID, arg.ListID, arg.UserIds)
	return err
}

const createApp = `-- name: CreateApp :one

INSERT INTO apps (name) VALUES ($1) RETURNING app_id, name, created_at
`

// Queries compiled by sqlc into internal/postgres/queries.
// Every query is scoped by app_id. Collections page by primary key: rows after @after, in order.
func (q *Queries) CreateApp(ctx context.Context, name string) (App, error) {
	row := q.db.QueryRow(ctx, createApp, name)
	var i App
	err := row.Scan(&i.AppID, &i.Name, &i.CreatedAt)
	return i, err
}

const createEndpoint = `-- name: CreateEndpoint :one
INSERT INTO endpoints (app_id, user_id, address, channel, provider)
VALUES ($1, $2, $3, $4, $5)
RETURNING app_id, endpoint_id, user_id, address, channel, provider
`

type CreateEndpointParams struct {
	AppID    pgtype.UUID
	UserID   string
	Address  string
	Channel  string
	Provider string
}

func (q *Queries) CreateEndpoint(ctx context.Context, arg CreateEndpointParams) (Endpoint, error) {
	row := q.db.QueryRow(ctx, createEndpoint,
		arg.AppID,
		arg.UserID,
		arg.Address,
		arg.Channel,
		arg.Provider,
	)
	var i Endpoint
	err := row.Scan(
		&i.AppID,
		&i.EndpointID,
		&i.UserID,
		&i.Address,
		&i.Channel,
		&i.Provider,
	)
	return i, err
}

const createList = `-- name: CreateList :one
INSERT INTO lists (app_id, name, description)
VALUES ($1, $2, $3)
RETURNING app_id, list_id, name, description, created_at
`

type CreateListParams struct {
	AppID       pgtype.UUID
	Name        string
	Description string
}

func (q *Queries) CreateList(ctx context.Context, arg CreateListParams) (List, error) {
	row := q.db.QueryRow(ctx, createList, arg.AppID, arg.Name, arg.Description)
	var i List
	err := row.Scan(
		&i.AppID,
		&i.ListID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const deleteEndpoint = `-- name: DeleteEndpoint :execrows
DELETE FROM endpoints WHERE app_id = $1 AND endpoint_id = $2
`

type DeleteEndpointParams struct {
	AppID      pgtype.UUID
	EndpointID pgtype.UUID
}

func (q *Queries) DeleteEndpoint(ctx context.Context, arg DeleteEndpointParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteEndpoint, arg.AppID, arg.EndpointID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteList = `-- name: DeleteList :execrows
DELETE FROM lists WHERE app_id = $1 AND list_id = $2
`

type DeleteListParams struct {
	AppID  pgtype.UUID
	ListID pgtype.UUID
}

func (q *Queries) DeleteList(ctx context.Context, arg DeleteListParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteList, arg.AppID, arg.ListID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteUser = `-- name: DeleteUser :execrows
DELETE FROM users WHERE app_id = $1 AND user_id = $2
`

type DeleteUserParams struct {
	AppID  pgtype.UUID
	UserID string
}

func (q *Queries) DeleteUser(ctx context.Context, arg DeleteUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUser, arg.AppID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const endpoint = `-- name: Endpoint :one
SELECT app_id, endpoint_id, user_id, address, channel, provider FROM endpoints WHERE app_id = $1 AND endpoint_id = $2
`

type EndpointParams struct {
	AppID      pgtype.UUID
	EndpointID pgtype.UUID
}

func (q *Queries) Endpoint(ctx context.Context, arg EndpointParams) (Endpoint, error) {
	row := q.db.QueryRow(ctx, endpoint, arg.AppID, arg.EndpointID)
	var i Endpoint
	err := row.Scan(
		&i.AppID,
		&i.EndpointID,
		&i.UserID,
		&i.Address,
		&i.Channel,
		&i.Provider,
	)
	return i, err
}

const endpoints = `-- name: Endpoints :many
SELECT app_id, endpoint_id, user_id, address, channel, provider FROM endpoints
WHERE app_id = $1 AND user_id = $2 AND endpoint_id > $3
ORDER BY endpoint_id
LIMIT $4
`

type EndpointsParams struct {
	AppID   pgtype.UUID
	UserID  string
	After   pgtype.UUID
	MaxRows int32
}

func (q *Queries) Endpoints(ctx context.Context, arg EndpointsParams) ([]Endpoint, error) {
	rows, err := q.db.Query(ctx, endpoints,
		arg.AppID,
		arg.UserID,
		arg.After,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Endpoint
	for rows.Next() {
		var i Endpoint
		if err := rows.Scan(
			&i.AppID,
			&i.EndpointID,
			&i.UserID,
			&i.Address,
			&i.Channel,
			&i.Provider,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertUser = `-- name: InsertUser :execrows
INSERT INTO users (app_id, user_id) VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type InsertUserParams struct {
	AppID  pgtype.UUID
	UserID string
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertUser, arg.AppID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const knownUsers = `-- name: KnownUsers :many
SELECT user_id FROM users WHERE app_id = $1 AND user_id = ANY($2::text[])
`

type KnownUsersParams struct {
	AppID   pgtype.UUID
	UserIds []string
}

func (q *Queries) KnownUsers(ctx context.Context, arg KnownUsersParams) ([]string, error) {
	rows, err := q.db.Query(ctx, knownUsers, arg.AppID, arg.UserIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var user_id string
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const list = `-- name: List :one
SELECT app_id, list_id, name, description, created_at FROM lists WHERE app_id = $1 AND list_id = $2
`

type ListParams struct {
	AppID  pgtype.UUID
	ListID pgtype.UUID
}

func (q *Queries) List(ctx context.Context, arg ListParams) (List, error) {
	row := q.db.QueryRow(ctx, list, arg.AppID, arg.ListID)
	var i List
	err := row.Scan(
		&i.AppID,
		&i.ListID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const lists = `-- name: Lists :many
SELECT app_id, list_id, name, description, created_at FROM lists
WHERE app_id = $1 AND list_id > $2
ORDER BY list_id
LIMIT $3
`

type ListsParams struct {
	AppID   pgtype.UUID
	After   pgtype.UUID
	MaxRows int32
}

func (q *Queries) Lists(ctx context.Context, arg ListsParams) ([]List, error) {
	rows, err := q.db.Query(ctx, lists, arg.AppID, arg.After, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []List
	for rows.Next() {
		var i List
		if err := rows.Scan(
			&i.AppID,
			&i.ListID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const members = `-- name: Members :many
SELECT user_id, added_at FROM list_members
WHERE app_id = $1 AND list_id = $2 AND user_id > $3
ORDER BY user_id
LIMIT $4
`

type MembersParams struct {
	AppID   pgtype.UUID
	ListID  pgtype.UUID
	After   string
	MaxRows int32
}

type MembersRow struct {
	UserID  string
	AddedAt time.Time
}

func (q *Queries) Members(ctx context.Context, arg MembersParams) ([]MembersRow, error) {
	rows, err := q.db.Query(ctx, members,
		arg.AppID,
		arg.ListID,
		arg.After,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MembersRow
	for rows.Next() {
		var i MembersRow
		if err := rows.Scan(&i.UserID, &i.AddedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeMember = `-- name: RemoveMember :exec
DELETE FROM list_members WHERE app_id = $1 AND list_id = $2 AND user_id = $3
`

type RemoveMemberParams struct {
	AppID  pgtype.UUID
	ListID pgtype.UUID
	UserID string
}

func (q *Queries) RemoveMember(ctx context.Context, arg RemoveMemberParams) error {
	_, err := q.db.Exec(ctx, removeMember, arg.AppID, arg.ListID, arg.UserID)
	return err
}

const updateEndpoint = `-- name: UpdateEndpoint :one
UPDATE endpoints
SET address = $1, channel = $2, provider = $3
WHERE app_id = $4 AND endpoint_id = $5
RETURNING app_id, endpoint_id, user_id, address, channel, provider
`

type UpdateEndpointParams struct {
	Address    string
	Channel    string
	Provider   string
	AppID      pgtype.UUID
	EndpointID pgtype.UUID
}

func (q *Queries) UpdateEndpoint(ctx context.Context, arg UpdateEndpointParams) (Endpoint, error) {
	row := q.db.QueryRow(ctx, updateEndpoint,
		arg.Address,
		arg.Channel,
		arg.Provider,
		arg.AppID,
		arg.EndpointID,
	)
	var i Endpoint
	err := row.Scan(
		&i.AppID,
		&i.EndpointID,
		&i.UserID,
		&i.Address,
		&i.Channel,
		&i.Provider,
	)
	return i, err
}

const updateList = `-- name: UpdateList :one
UPDATE lists
SET name = $1, description = $2
WHERE app_id = $3 AND list_id = $4
RETURNING app_id, list_id, name, description, created_at
`

type UpdateListParams struct {
	Name        string
	Description string
	AppID       pgtype.UUID
	ListID      pgtype.UUID
}

func (q *Queries) UpdateList(ctx context.Context, arg UpdateListParams) (List, error) {
	row := q.db.QueryRow(ctx, updateList,
		arg.Name,
		arg.Description,
		arg.AppID,
		arg.ListID,
	)
	var i List
	err := row.Scan(
		&i.AppID,
		&i.ListID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const user = `-- name: User :one
SELECT app_id, user_id, created_at FROM users WHERE app_id = $1 AND user_id = $2
`

type UserParams struct {
	AppID  pgtype.UUID
	UserID string
}

func (q *Queries) User(ctx context.Context, arg UserParams) (User, error) {
	row := q.db.QueryRow(ctx, user, arg.AppID, arg.UserID)
	var i User
	err := row.Scan(&i.AppID, &i.UserID, &i.CreatedAt)
	return i, err
}

const users = `-- name: Users :many
SELECT app_id, user_id, created_at FROM users
WHERE app_id = $1 AND user_id > $2
ORDER BY user_id
LIMIT $3
`

type UsersParams struct {
	AppID   pgtype.UUID
	After   string
	MaxRows int32
}

func (q *Queries) Users(ctx context.Context, arg UsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, users, arg.AppID, arg.After, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(&i.AppID, &i.UserID, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
