// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package queries

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const addMembers = `-- name: AddMembers :exec
INSERT INTO list_members (app_id, list_id, user_id)
SELECT $1::uuid, $2::uuid, unnest($3::text[])
ON CONFLICT DO NOTHING
`

type AddMembersParams struct {
	AppID   pgtype.UUID
	ListID  pgtype.UUID
	UserIds []string
}

func (q *Queries) AddMembers(ctx context.Context, arg AddMembersParams) error {
	_, err := q.db.Exec(ctx, addMembers, arg.AppID, arg.ListID, arg.UserIds)
	return err
}

const advanceFanout = `-- name: AdvanceFanout :execrows
WITH advanced AS (
    UPDATE fanouts f
    SET user_cursor = $2, run_after = now() + make_interval(secs => $3)
    WHERE f.app_id = $4 AND f.job_id = $5 AND f.user_cursor = $6
    RETURNING f.app_id, f.job_id
), counted AS (
    UPDATE jobs j
    SET status = 'dispatching', queued = j.queued + $1, updated_at = now()
    FROM advanced a
    WHERE j.app_id = a.app_id AND j.job_id = a.job_id
)
INSERT INTO usage_daily (app_id, day, queued)
SELECT a.app_id, current_date, $1 FROM advanced a
ON CONFLICT (app_id, day) DO UPDATE SET queued = usage_daily.queued + EXCLUDED.queued
`

type AdvanceFanoutParams struct {
	Published      int64
	UserCursor     string
	LeaseSecs      float64
	AppID          pgtype.UUID
	JobID          pgtype.UUID
	PreviousCursor string
}

// One statement, so the cursor, the job's count and the app's usage move together. It
// also renews the lease. Nothing changes, and no row is affected, unless the cursor is
// still at @previous_cursor: a dispatcher that lost its lease must not count a page twice.
func (q *Queries) AdvanceFanout(ctx context.Context, arg AdvanceFanoutParams) (int64, error) {
	result, err := q.db.Exec(ctx, advanceFanout,
		arg.Published,
		arg.UserCursor,
		arg.LeaseSecs,
		arg.AppID,
		arg.JobID,
		arg.PreviousCursor,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const claimFanout = `-- name: ClaimFanout :one
WITH claimed AS (
    UPDATE fanouts f
    SET run_after = now() + make_interval(secs => $1)
    WHERE (f.app_id, f.job_id) = (
        SELECT d.app_id, d.job_id FROM fanouts d
        WHERE d.run_after <= now()
        ORDER BY d.run_after
        LIMIT 1
        FOR UPDATE SKIP LOCKED
    )
    RETURNING f.app_id, f.job_id, f.user_cursor
)
SELECT c.app_id, c.job_id, c.user_cursor, j.priority, j.user_ids, j.list_id, j.title, j.body
FROM claimed c
JOIN jobs j ON j.app_id = c.app_id AND j.job_id = c.job_id
`

type ClaimFanoutRow struct {
	AppID      pgtype.UUID
	JobID      pgtype.UUID
	UserCursor string
	Priority   string
	UserIds    []string
	ListID     pgtype.UUID
	Title      string
	Body       string
}

// Takes the fan-out that has been due longest and keeps the others off it for the lease.
// SKIP LOCKED makes dispatchers that claim at the same moment take different ones.
func (q *Queries) ClaimFanout(ctx context.Context, leaseSecs float64) (ClaimFanoutRow, error) {
	row := q.db.QueryRow(ctx, claimFanout, leaseSecs)
	var i ClaimFanoutRow
	err := row.Scan(
		&i.AppID,
		&i.JobID,
		&i.UserCursor,
		&i.Priority,
		&i.UserIds,
		&i.ListID,
		&i.Title,
		&i.Body,
	)
	return i, err
}

const createApp = `-- name: CreateApp :one

INSERT INTO apps (name) VALUES ($1) RETURNING app_id, name, created_at, daily_quota
`

// Queries compiled by sqlc into internal/postgres/queries.
// Every query is scoped by app_id. Collections page by primary key: rows after @after, in order.
func (q *Queries) CreateApp(ctx context.Context, name string) (App, error) {
	row := q.db.QueryRow(ctx, createApp, name)
	var i App
	err := row.Scan(
		&i.AppID,
		&i.Name,
		&i.CreatedAt,
		&i.DailyQuota,
	)
	return i, err
}

const createEndpoint = `-- name: CreateEndpoint :one
INSERT INTO endpoints (app_id, user_id, address, channel, provider)
VALUES ($1, $2, $3, $4, $5)
RETURNING app_id, endpoint_id, user_id, address, channel, provider
`

type CreateEndpointParams struct {
	AppID    pgtype.UUID
	UserID   string
	Address  string
	Channel  string
	Provider string
}

func (q *Queries) CreateEndpoint(ctx context.Context, arg CreateEndpointParams) (Endpoint, error) {
	row := q.db.QueryRow(ctx, createEndpoint,
		arg.AppID,
		arg.UserID,
		arg.Address,
		arg.Channel,
		arg.Provider,
	)
	var i Endpoint
	err := row.Scan(
		&i.AppID,
		&i.EndpointID,
		&i.UserID,
		&i.Address,
		&i.Channel,
		&i.Provider,
	)
	return i, err
}

const createList = `-- name: CreateList :one
INSERT INTO lists (app_id, name, description)
VALUES ($1, $2, $3)
RETURNING app_id, list_id, name, description, created_at
`

type CreateListParams struct {
	AppID       pgtype.UUID
	Name        string
	Description string
}

func (q *Queries) CreateList(ctx context.Context, arg CreateListParams) (List, error) {
	row := q.db.QueryRow(ctx, createList, arg.AppID, arg.Name, arg.Description)
	var i List
	err := row.Scan(
		&i.AppID,
		&i.ListID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const deleteEndpoint = `-- name: DeleteEndpoint :execrows
DELETE FROM endpoints WHERE app_id = $1 AND endpoint_id = $2
`

type DeleteEndpointParams struct {
	AppID      pgtype.UUID
	EndpointID pgtype.UUID
}

func (q *Queries) DeleteEndpoint(ctx context.Context, arg DeleteEndpointParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteEndpoint, arg.AppID, arg.EndpointID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteList = `-- name: DeleteList :execrows
DELETE FROM lists WHERE app_id = $1 AND list_id = $2
`

type DeleteListParams struct {
	AppID  pgtype.UUID
	ListID pgtype.UUID
}

func (q *Queries) DeleteList(ctx context.Context, arg DeleteListParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteList, arg.AppID, arg.ListID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteUser = `-- name: DeleteUser :execrows
DELETE FROM users WHERE app_id = $1 AND user_id = $2
`

type DeleteUserParams struct {
	AppID  pgtype.UUID
	UserID string
}

func (q *Queries) DeleteUser(ctx context.Context, arg DeleteUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUser, arg.AppID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const endpoint = `-- name: Endpoint :one
SELECT app_id, endpoint_id, user_id, address, channel, provider FROM endpoints WHERE app_id = $1 AND endpoint_id = $2
`

type EndpointParams struct {
	AppID      pgtype.UUID
	EndpointID pgtype.UUID
}

func (q *Queries) Endpoint(ctx context.Context, arg EndpointParams) (Endpoint, error) {
	row := q.db.QueryRow(ctx, endpoint, arg.AppID, arg.EndpointID)
	var i Endpoint
	err := row.Scan(
		&i.AppID,
		&i.EndpointID,
		&i.UserID,
		&i.Address,
		&i.Channel,
		&i.Provider,
	)
	return i, err
}

const endpoints = `-- name: Endpoints :many
SELECT app_id, endpoint_id, user_id, address, channel, provider FROM endpoints
WHERE app_id = $1 AND user_id = $2 AND endpoint_id > $3
ORDER BY endpoint_id
LIMIT $4
`

type EndpointsParams struct {
	AppID   pgtype.UUID
	UserID  string
	After   pgtype.UUID
	MaxRows int32
}

func (q *Queries) Endpoints(ctx context.Context, arg EndpointsParams) ([]Endpoint, error) {
	rows, err := q.db.Query(ctx, endpoints,
		arg.AppID,
		arg.UserID,
		arg.After,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Endpoint
	for rows.Next() {
		var i Endpoint
		if err := rows.Scan(
			&i.AppID,
			&i.EndpointID,
			&i.UserID,
			&i.Address,
			&i.Channel,
			&i.Provider,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const fanoutPage = `-- name: FanoutPage :many
WITH page AS (
    SELECT t.user_id FROM (
        (SELECT m.user_id FROM list_members m
         WHERE m.app_id = $1 AND m.list_id = $2 AND m.user_id > $3
         ORDER BY m.user_id LIMIT $4)
        UNION
        (SELECT u.user_id FROM unnest($5::text[]) AS u(user_id)
         WHERE u.user_id > $3
         ORDER BY u.user_id LIMIT $4)
    ) t
    ORDER BY t.user_id
    LIMIT $4
)
SELECT p.user_id::text AS user_id, e.endpoint_id, e.channel, e.provider, e.address
FROM page p
LEFT JOIN endpoints e ON e.app_id = $1 AND e.user_id = p.user_id
ORDER BY p.user_id, e.endpoint_id
`

type FanoutPageParams struct {
	AppID    pgtype.UUID
	ListID   pgtype.UUID
	After    string
	MaxUsers int32
	UserIds  []string
}

type FanoutPageRow struct {
	UserID     string
	EndpointID pgtype.UUID
	Channel    pgtype.Text
	Provider   pgtype.Text
	Address    pgtype.Text
}

// The next @max_users users of a job's audience after @after, each once, with their
// endpoints: one row per endpoint, and a row without one for a user that has none, so
// that the caller sees every user the page covers.
//
// It is three index range scans and no more. The members come in order from the primary
// key of list_members, the named users need no table at all, and the endpoints of the
// page are one range of endpoints_fanout_idx. Each branch is limited on its own so that
// it stops after one page.
func (q *Queries) FanoutPage(ctx context.Context, arg FanoutPageParams) ([]FanoutPageRow, error) {
	rows, err := q.db.Query(ctx, fanoutPage,
		arg.AppID,
		arg.ListID,
		arg.After,
		arg.MaxUsers,
		arg.UserIds,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FanoutPageRow
	for rows.Next() {
		var i FanoutPageRow
		if err := rows.Scan(
			&i.UserID,
			&i.EndpointID,
			&i.Channel,
			&i.Provider,
			&i.Address,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const finishFanout = `-- name: FinishFanout :execrows
WITH finished AS (
    DELETE FROM fanouts f
    WHERE f.app_id = $2 AND f.job_id = $3 AND f.user_cursor = $4
    RETURNING f.app_id, f.job_id
), counted AS (
    UPDATE jobs j
    SET status = 'dispatched', queued = j.queued + $1, updated_at = now()
    FROM finished f
    WHERE j.app_id = f.app_id AND j.job_id = f.job_id
)
INSERT INTO usage_daily (app_id, day, queued)
SELECT f.app_id, current_date, $1 FROM finished f
ON CONFLICT (app_id, day) DO UPDATE SET queued = usage_daily.queued + EXCLUDED.queued
`

type FinishFanoutParams struct {
	Published      int64
	AppID          pgtype.UUID
	JobID          pgtype.UUID
	PreviousCursor string
}

// AdvanceFanout for the last page: instead of moving the cursor it deletes the fan-out.
func (q *Queries) FinishFanout(ctx context.Context, arg FinishFanoutParams) (int64, error) {
	result, err := q.db.Exec(ctx, finishFanout,
		arg.Published,
		arg.AppID,
		arg.JobID,
		arg.PreviousCursor,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertJob = `-- name: InsertJob :one
WITH job AS (
    INSERT INTO jobs (app_id, priority, user_ids, list_id, title, body, idempotency_key)
    VALUES ($1, $2, $3, $4, $5, $6, $7)
    ON CONFLICT (app_id, idempotency_key) DO NOTHING
    RETURNING app_id, job_id, status, priority, user_ids, list_id, title, body, idempotency_key, queued, created_at, updated_at
), fanout AS (
    INSERT INTO fanouts (app_id, job_id) SELECT job.app_id, job.job_id FROM job
)
SELECT app_id, job_id, status, priority, user_ids, list_id, title, body, idempotency_key, queued, created_at, updated_at FROM job
`

type InsertJobParams struct {
	AppID          pgtype.UUID
	Priority       string
	UserIds        []string
	ListID         pgtype.UUID
	Title          string
	Body           string
	IdempotencyKey pgtype.Text
}

type InsertJobRow struct {
	AppID          pgtype.UUID
	JobID          pgtype.UUID
	Status         string
	Priority       string
	UserIds        []string
	ListID         pgtype.UUID
	Title          string
	Body           string
	IdempotencyKey pgtype.Text
	Queued         int64
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

// Stores a job together with the fan-out it is owed. Returns no row when the app has
// already used the idempotency key.
func (q *Queries) InsertJob(ctx context.Context, arg InsertJobParams) (InsertJobRow, error) {
	row := q.db.QueryRow(ctx, insertJob,
		arg.AppID,
		arg.Priority,
		arg.UserIds,
		arg.ListID,
		arg.Title,
		arg.Body,
		arg.IdempotencyKey,
	)
	var i InsertJobRow
	err := row.Scan(
		&i.AppID,
		&i.JobID,
		&i.Status,
		&i.Priority,
		&i.UserIds,
		&i.ListID,
		&i.Title,
		&i.Body,
		&i.IdempotencyKey,
		&i.Queued,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertUser = `-- name: InsertUser :execrows
INSERT INTO users (app_id, user_id) VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type InsertUserParams struct {
	AppID  pgtype.UUID
	UserID string
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertUser, arg.AppID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const job = `-- name: Job :one
SELECT app_id, job_id, status, priority, user_ids, list_id, title, body, idempotency_key, queued, created_at, updated_at FROM jobs WHERE app_id = $1 AND job_id = $2
`

type JobParams struct {
	AppID pgtype.UUID
	JobID pgtype.UUID
}

func (q *Queries) Job(ctx context.Context, arg JobParams) (Job, error) {
	row := q.db.QueryRow(ctx, job, arg.AppID, arg.JobID)
	var i Job
	err := row.Scan(
		&i.AppID,
		&i.JobID,
		&i.Status,
		&i.Priority,
		&i.UserIds,
		&i.ListID,
		&i.Title,
		&i.Body,
		&i.IdempotencyKey,
		&i.Queued,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const jobByIdempotencyKey = `-- name: JobByIdempotencyKey :one
SELECT app_id, job_id, status, priority, user_ids, list_id, title, body, idempotency_key, queued, created_at, updated_at FROM jobs WHERE app_id = $1 AND idempotency_key = $2
`

type JobByIdempotencyKeyParams struct {
	AppID          pgtype.UUID
	IdempotencyKey pgtype.Text
}

func (q *Queries) JobByIdempotencyKey(ctx context.Context, arg JobByIdempotencyKeyParams) (Job, error) {
	row := q.db.QueryRow(ctx, jobByIdempotencyKey, arg.AppID, arg.IdempotencyKey)
	var i Job
	err := row.Scan(
		&i.AppID,
		&i.JobID,
		&i.Status,
		&i.Priority,
		&i.UserIds,
		&i.ListID,
		&i.Title,
		&i.Body,
		&i.IdempotencyKey,
		&i.Queued,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const jobs = `-- name: Jobs :many
SELECT app_id, job_id, status, priority, user_ids, list_id, title, body, idempotency_key, queued, created_at, updated_at FROM jobs
WHERE app_id = $1 AND job_id > $2
ORDER BY job_id
LIMIT $3
`

type JobsParams struct {
	AppID   pgtype.UUID
	After   pgtype.UUID
	MaxRows int32
}

func (q *Queries) Jobs(ctx context.Context, arg JobsParams) ([]Job, error) {
	rows, err := q.db.Query(ctx, jobs, arg.AppID, arg.After, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.AppID,
			&i.JobID,
			&i.Status,
			&i.Priority,
			&i.UserIds,
			&i.ListID,
			&i.Title,
			&i.Body,
			&i.IdempotencyKey,
			&i.Queued,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const knownUsers = `-- name: KnownUsers :many
SELECT user_id FROM users WHERE app_id = $1 AND user_id = ANY($2::text[])
`

type KnownUsersParams struct {
	AppID   pgtype.UUID
	UserIds []string
}

func (q *Queries) KnownUsers(ctx context.Context, arg KnownUsersParams) ([]string, error) {
	rows, err := q.db.Query(ctx, knownUsers, arg.AppID, arg.UserIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var user_id string
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const list = `-- name: List :one
SELECT app_id, list_id, name, description, created_at FROM lists WHERE app_id = $1 AND list_id = $2
`

type ListParams struct {
	AppID  pgtype.UUID
	ListID pgtype.UUID
}

func (q *Queries) List(ctx context.Context, arg ListParams) (List, error) {
	row := q.db.QueryRow(ctx, list, arg.AppID, arg.ListID)
	var i List
	err := row.Scan(
		&i.AppID,
		&i.ListID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const lists = `-- name: Lists :many
SELECT app_id, list_id, name, description, created_at FROM lists
WHERE app_id = $1 AND list_id > $2
ORDER BY list_id
LIMIT $3
`

type ListsParams struct {
	AppID   pgtype.UUID
	After   pgtype.UUID
	MaxRows int32
}

func (q *Queries) Lists(ctx context.Context, arg ListsParams) ([]List, error) {
	rows, err := q.db.Query(ctx, lists, arg.AppID, arg.After, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []List
	for rows.Next() {
		var i List
		if err := rows.Scan(
			&i.AppID,
			&i.ListID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const members = `-- name: Members :many
SELECT user_id, added_at FROM list_members
WHERE app_id = $1 AND list_id = $2 AND user_id > $3
ORDER BY user_id
LIMIT $4
`

type MembersParams struct {
	AppID   pgtype.UUID
	ListID  pgtype.UUID
	After   string
	MaxRows int32
}

type MembersRow struct {
	UserID  string
	AddedAt time.Time
}

func (q *Queries) Members(ctx context.Context, arg MembersParams) ([]MembersRow, error) {
	rows, err := q.db.Query(ctx, members,
		arg.AppID,
		arg.ListID,
		arg.After,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MembersRow
	for rows.Next() {
		var i MembersRow
		if err := rows.Scan(&i.UserID, &i.AddedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const quota = `-- name: Quota :one
SELECT a.daily_quota, COALESCE(u.queued, 0)::bigint AS used
FROM apps a
LEFT JOIN usage_daily u ON u.app_id = a.app_id AND u.day = current_date
WHERE a.app_id = $1
`

type QuotaRow struct {
	DailyQuota int64
	Used       int64
}

func (q *Queries) Quota(ctx context.Context, appID pgtype.UUID) (QuotaRow, error) {
	row := q.db.QueryRow(ctx, quota, appID)
	var i QuotaRow
	err := row.Scan(&i.DailyQuota, &i.Used)
	return i, err
}

const removeMember = `-- name: RemoveMember :exec
DELETE FROM list_members WHERE app_id = $1 AND list_id = $2 AND user_id = $3
`

type RemoveMemberParams struct {
	AppID  pgtype.UUID
	ListID pgtype.UUID
	UserID string
}

func (q *Queries) RemoveMember(ctx context.Context, arg RemoveMemberParams) error {
	_, err := q.db.Exec(ctx, removeMember, arg.AppID, arg.ListID, arg.UserID)
	return err
}

const updateEndpoint = `-- name: UpdateEndpoint :one
UPDATE endpoints
SET address = $1, channel = $2, provider = $3
WHERE app_id = $4 AND endpoint_id = $5
RETURNING app_id, endpoint_id, user_id, address, channel, provider
`

type UpdateEndpointParams struct {
	Address    string
	Channel    string
	Provider   string
	AppID      pgtype.UUID
	EndpointID pgtype.UUID
}

func (q *Queries) UpdateEndpoint(ctx context.Context, arg UpdateEndpointParams) (Endpoint, error) {
	row := q.db.QueryRow(ctx, updateEndpoint,
		arg.Address,
		arg.Channel,
		arg.Provider,
		arg.AppID,
		arg.EndpointID,
	)
	var i Endpoint
	err := row.Scan(
		&i.AppID,
		&i.EndpointID,
		&i.UserID,
		&i.Address,
		&i.Channel,
		&i.Provider,
	)
	return i, err
}

const updateList = `-- name: UpdateList :one
UPDATE lists
SET name = $1, description = $2
WHERE app_id = $3 AND list_id = $4
RETURNING app_id, list_id, name, description, created_at
`

type UpdateListParams struct {
	Name        string
	Description string
	AppID       pgtype.UUID
	ListID      pgtype.UUID
}

func (q *Queries) UpdateList(ctx context.Context, arg UpdateListParams) (List, error) {
	row := q.db.QueryRow(ctx, updateList,
		arg.Name,
		arg.Description,
		arg.AppID,
		arg.ListID,
	)
	var i List
	err := row.Scan(
		&i.AppID,
		&i.ListID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const user = `-- name: User :one
SELECT app_id, user_id, created_at FROM users WHERE app_id = $1 AND user_id = $2
`

type UserParams struct {
	AppID  pgtype.UUID
	UserID string
}

func (q *Queries) User(ctx context.Context, arg UserParams) (User, error) {
	row := q.db.QueryRow(ctx, user, arg.AppID, arg.UserID)
	var i User
	err := row.Scan(&i.AppID, &i.UserID, &i.CreatedAt)
	return i, err
}

const users = `-- name: Users :many
SELECT app_id, user_id, created_at FROM users
WHERE app_id = $1 AND user_id > $2
ORDER BY user_id
LIMIT $3
`

type UsersParams struct {
	AppID   pgtype.UUID
	After   string
	MaxRows int32
}

func (q *Queries) Users(ctx context.Context, arg UsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, users, arg.AppID, arg.After, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(&i.AppID, &i.UserID, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
