// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/francobatta/iol-challenge/notification-system/api/internal/insight (interfaces: Querier)
//
// Generated by this command:
//
//	mockgen -destination=insighttest/mock.go -package=insighttest . Querier
//

// Package insighttest is a generated GoMock package.
package insighttest

import (
	context "context"
	reflect "reflect"
	time "time"

	insight "github.com/francobatta/iol-challenge/notification-system/api/internal/insight"
	gomock "go.uber.org/mock/gomock"
)

// MockQuerier is a mock of Querier interface.
type MockQuerier struct {
	ctrl     *gomock.Controller
	recorder *MockQuerierMockRecorder
	isgomock struct{}
}

// MockQuerierMockRecorder is the mock recorder for MockQuerier.
type MockQuerierMockRecorder struct {
	mock *MockQuerier
}

// NewMockQuerier creates a new mock instance.
func NewMockQuerier(ctrl *gomock.Controller) *MockQuerier {
	mock := &MockQuerier{ctrl: ctrl}
	mock.recorder = &MockQuerierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuerier) EXPECT() *MockQuerierMockRecorder {
	return m.recorder
}

// Instant mocks base method.
func (m *MockQuerier) Instant(ctx context.Context, query string, at time.Time) ([]insight.Sample, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Instant", ctx, query, at)
	ret0, _ := ret[0].([]insight.Sample)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Instant indicates an expected call of Instant.
func (mr *MockQuerierMockRecorder) Instant(ctx, query, at any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Instant", reflect.TypeOf((*MockQuerier)(nil).Instant), ctx, query, at)
}

// Range mocks base method.
func (m *MockQuerier) Range(ctx context.Context, query string, start, end time.Time, step time.Duration) ([]insight.Series, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Range", ctx, query, start, end, step)
	ret0, _ := ret[0].([]insight.Series)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Range indicates an expected call of Range.
func (mr *MockQuerierMockRecorder) Range(ctx, query, start, end, step any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Range", reflect.TypeOf((*MockQuerier)(nil).Range), ctx, query, start, end, step)
}
